DOCKER=docker


build:
	$(DOCKER) build --no-cache -t gnucobol:1.0 -t gnucobol:latest .

build-version:
	$(DOCKER) build -t gnucobol:1.0 -t gnucobol:latest --build-arg COBC_VERSION=3.1.2 .

run:
	$(DOCKER) run -v gnucobol:/install:rw gnucobol:1.0

volumes:
	$(DOCKER) volume create --driver=local --opt type=none --opt o=bind --opt device="$(shell pwd)/home" gnucobol

layer:
	-rm cobol-layer.zip
	cd home && zip -r ../cobol-layer.zip gnucobol

clean:
	$(DOCKER) container prune
	$(DOCKER) image prune
	$(DOCKER) volume rm gnucobol